### ISSUE TITLE
Better error messages when constructing data sets

### ISSUE THREAD

**Issue by tlamadon** [tlamadon/bipartitepandas#1]
If one of the 4 required column is missing or has the wrong type, we should provide a message that says exactly what the issue is. Right now it just throws an error about wrong type if you define the wage as w instead of y.

I think we should also add a construction method that simply takes the 4 required columns as input argument, ie 

```python
Bipartite(i= I, j= J, t= T , y=Y )
```

where I, J, T and Y are simply numpy vectors.

**Comment by adamoppenheimer** [comment]
The most recent commit added the new constructor. I still need to update error messages.

**Comment by adamoppenheimer** [comment]
Errors are now clearer about whether a column is missing and if it has the incorrect datatype.
